protected/modules/lab/models/RequestCode.php
<?php

/**
 * This is the model class for table "requestcode".
 *
 * The followings are the available columns in table 'requestcode':
 * @property integer $id
 * @property string $requestRefNum
 * @property integer $labId
 * @property integer $number
 * @property integer $year
 * @property integer $cancelled
 */
class Requestcode extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'requestcode';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			//array('requestRefNum, rstl_id, labId, number, year, cancelled', 'required'),
			array('rstl_id, labId, number, year', 'required'),
			array('rstl_id, labId, number, year, cancelled', 'numerical', 'integerOnly'=>true),
			array('requestRefNum', 'length', 'max'=>50),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, requestRefNum, rstl_id, labId, number, year, cancelled', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'requestRefNum' => 'Request Ref Num',
			'labId' => 'Lab',
			'number' => 'Number',
			'sampleCode' => 'Sample Code',
			'year' => 'Year',
			'cancelled' => 'Cancelled',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('requestRefNum',$this->requestRefNum,true);
		$criteria->compare('labId',$this->labId);
		$criteria->compare('number',$this->number);
		$criteria->compare('year',$this->year);
		$criteria->compare('cancelled',$this->cancelled);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * @return CDbConnection the database connection used for this class
	 */
	public function getDbConnection()
	{
		return Yii::app()->ulimsDb;
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Requestcode the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/modules/lab/controllers/RequestcodeController.php
<?php

class RequestcodeController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		/*return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);*/
		return array('rights');
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}
	
	public function actionTest(){
			$requestCodes = array();
			foreach($_POST['Requestcode']['number'] as $number){
				$code = array('count'=>$number);
				array_push($requestCodes, $code);
			}
			//echo count($_POST['Requestcode']['number']);
			//print_r($requestCodes);
			//echo $_POST['Requestcode']['number'][2] + $_POST['Requestcode']['number'][0];
			print_r($_POST['sampleCode']);
			//echo $_POST['sapleCode']." ";
	} 
	
	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model = new Requestcode;
		$labs = Lab::model()->findAll();
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Requestcode']))
		{
			$model->attributes=$_POST['Requestcode'];
			
			//$count = count($_POST['Requestcode']['number']);
			$index = 0;
			$labs = Lab::model()->findAll();
			
			foreach($labs as $lab){
				$requestcode = new Requestcode;
				$requestcode->rstl_id = $this->getRstlId();
				$requestcode->labId = $lab->id;
				$requestcode->number = $_POST['Requestcode']['number'][$index];
				$requestcode->year = $_POST['Requestcode']['year'];
				$requestcode->cancelled = 0;
				$requestcode->save();
				$index += 1;
			}
			
			$index2 = 0;
			foreach($labs as $lab){
				$samplecode = new Samplecode;
				$samplecode->rstl_id = $this->getRstlId();
				$samplecode->labId = $lab->id;
				$samplecode->number = $_POST['sampleCode'][$index2];
				$samplecode->year = $_POST['Requestcode']['year'];
				$samplecode->cancelled = 0;
				$samplecode->save();
				$index2 += 1;
			}
			
			$this->redirect($this->createUrl('request/admin'));
		}

		$this->render('create',array(
			'model'=>$model,
			'labs'=>$labs
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Requestcode']))
		{
			$model->attributes=$_POST['Requestcode'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Requestcode');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Requestcode('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Requestcode']))
			$model->attributes=$_GET['Requestcode'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Requestcode the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Requestcode::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Requestcode $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='requestcode-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/lab/views/requestcode/_form.php
<?php
/* @var $this RequestcodeController */
/* @var $model Requestcode */
/* @var $form CActiveForm */
?>

<div class="form wide">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'requestcode-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>
	<p class="note">The system must initialize codes before creating Requests. The <span class="required">last entries for the previous month</span> should be indicated here.</p>
	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php //echo $form->labelEx($model,'requestRefNum'); ?>
		<?php //echo $form->textField($model,'requestRefNum',array('size'=>50,'maxlength'=>50)); ?>
		<?php //echo $form->error($model,'requestRefNum'); ?>
	</div>
	<div class="row">
		<?php //echo $form->labelEx($model,'rstl_id'); ?>
		<?php //echo $form->textField($model,'rstl_id'); ?>
		<?php //echo $form->error($model,'rstl_id'); ?>
	</div>
	
	<?php foreach($labs as $lab):?>
	
		<div class="row">
			<?php //echo $form->labelEx($model,'labId'); ?>
			<?php //echo $form->dropDownList($model,'labId', Lab::listdata(), array()); ?>
			<?php //echo CHtml::dropDownList(labId, $lab->id, Lab::listdata());?>
			<?php //echo $form->error($model,'labId'); ?>
		</div>
		
		<div class="row">
			<?php echo $form->labelEx($model, $lab->labName); ?>
			<?php echo $form->textField($model,'number[]'); ?>
			<?php echo $form->error($model,'number'); ?>
		</div>
		
		<div class="row">	
			<?php echo $form->labelEx($model, 'sampleCode'); ?>
			<?php echo CHtml::textField('sampleCode[]'); ?>
		</div>
		<br/>
	<?php endforeach;?>

	<div class="row">
		<?php echo $form->labelEx($model,'year'); ?>
		<?php echo $form->dropDownList($model,'year',  CHtml::listData($this->getYear(), 'index', 'year')); ?>
		<?php echo $form->error($model,'year'); ?>
	</div>

	<div class="row">
		<?php //echo $form->labelEx($model,'cancelled'); ?>
		<?php //echo $form->textField($model,'cancelled'); ?>
		<?php //echo $form->error($model,'cancelled'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'/*,
				array(
						'ajax'=>array(
							'type'=>'POST',
							'url'=>$this->createUrl('requestcode/test'),
							'success'=>'function(){return false;}',
						 ))*/
				);
		 ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/modules/lab/views/requestcode/_search.php
<?php
/* @var $this RequestcodeController */
/* @var $model Requestcode */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'requestRefNum'); ?>
		<?php echo $form->textField($model,'requestRefNum',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'rstl_id'); ?>
		<?php echo $form->textField($model,'rstl_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'labId'); ?>
		<?php echo $form->textField($model,'labId'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'number'); ?>
		<?php echo $form->textField($model,'number'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'year'); ?>
		<?php echo $form->textField($model,'year'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'cancelled'); ?>
		<?php echo $form->textField($model,'cancelled'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/lab/views/requestcode/_view.php
<?php
/* @var $this RequestcodeController */
/* @var $data Requestcode */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('requestRefNum')); ?>:</b>
	<?php echo CHtml::encode($data->requestRefNum); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('rstl_id')); ?>:</b>
	<?php echo CHtml::encode($data->rstl_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('labId')); ?>:</b>
	<?php echo CHtml::encode($data->labId); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('number')); ?>:</b>
	<?php echo CHtml::encode($data->number); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('year')); ?>:</b>
	<?php echo CHtml::encode($data->year); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('cancelled')); ?>:</b>
	<?php echo CHtml::encode($data->cancelled); ?>
	<br />


</div>

protected/modules/lab/views/requestcode/admin.php
<?php
/* @var $this RequestcodeController */
/* @var $model Requestcode */

$this->breadcrumbs=array(
	'Requestcodes'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Requestcode', 'url'=>array('index')),
	array('label'=>'Create Requestcode', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#requestcode-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Requestcodes</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'requestcode-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'requestRefNum',
		'rstl_id',
		'labId',
		'number',
		'year',
		/*
		'cancelled',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/modules/lab/views/requestcode/create.php
<?php
/* @var $this RequestcodeController */
/* @var $model Requestcode */

$this->breadcrumbs=array(
	'Requestcodes'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Requestcode', 'url'=>array('index')),
	array('label'=>'Manage Requestcode', 'url'=>array('admin')),
);
?>

<h1>Initialize Request and Sample Codes</h1>

<?php 
	$this->renderPartial('_form', 
	array(
		'model'=>$model,
		'labs'=>$labs
	)); 
?>

protected/modules/lab/views/requestcode/index.php
<?php
/* @var $this RequestcodeController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Requestcodes',
);

$this->menu=array(
	array('label'=>'Create Requestcode', 'url'=>array('create')),
	array('label'=>'Manage Requestcode', 'url'=>array('admin')),
);
?>

<h1>Requestcodes</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/modules/lab/views/requestcode/update.php
<?php
/* @var $this RequestcodeController */
/* @var $model Requestcode */

$this->breadcrumbs=array(
	'Requestcodes'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Requestcode', 'url'=>array('index')),
	array('label'=>'Create Requestcode', 'url'=>array('create')),
	array('label'=>'View Requestcode', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Requestcode', 'url'=>array('admin')),
);
?>

<h1>Update Requestcode <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/lab/views/requestcode/view.php
<?php
/* @var $this RequestcodeController */
/* @var $model Requestcode */

$this->breadcrumbs=array(
	'Requestcodes'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List Requestcode', 'url'=>array('index')),
	array('label'=>'Create Requestcode', 'url'=>array('create')),
	array('label'=>'Update Requestcode', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Requestcode', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Requestcode', 'url'=>array('admin')),
);
?>

<h1>View Requestcode #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'requestRefNum',
		'rstl_id',
		'labId',
		'number',
		'year',
		'cancelled',
	),
)); ?>